### ISSUE TITLE
incorrect suggestions

### ISSUE THREAD

**Issue by nikolskiy** [logisticAKB/word-predictor#2]
It looks like the suggestions list is incorrect. For example when I enter letter `t` the script returns:
action
active
address
adequate
adjustment
administration
administrator
admire
admission
admit
adolescent
adopt
adult
advanced
advantage
bar

Obviously it doesn't start with `t` some words even don't contain `t` like `advanced` or `bar`

**Comment by logisticAKB** [comment]
![11](https://user-images.githubusercontent.com/42612598/52533289-96f9ce80-2d53-11e9-9f3e-9cbb56202a99.JPG)
I just tried it and in returned nothing

**Comment by nikolskiy** [comment]
![wrong-suggestions](https://user-images.githubusercontent.com/1272429/52534002-7c2c5780-2d5d-11e9-9cce-59a449c5fd0f.png)
That is what I get.

**Comment by nikolskiy** [comment]
Space seems to work correctly but after that I get:
![word-suggestions2](https://user-images.githubusercontent.com/1272429/52534040-27d5a780-2d5e-11e9-9f8a-f1fbf42dfbcd.png)

**Comment by logisticAKB** [comment]
Yeah, looks like this code works only under windows

```python
def print_words(event):
    new_char = chr(event.keycode).lower()
    if new_char.isalpha():
        gui.set_cur_word(gui.get_cur_word() + new_char)
    elif new_char.isspace():
        gui.set_cur_word('')
    elif event.keycode == 8:
        word = gui.get_cur_word()
        gui.set_cur_word(word[:len(word) - 1])
    pt.query(pt.root, gui.get_cur_word(), '')
    print("|---------------------------------------|")

root.bind("<Key>", print_words)
```
On linux this code should be different, because linux and windows have different keycodes
So I guess it's bad idea use keycodes

**Comment by logisticAKB** [comment]
Fixed.
